version: '3'
services:
  search_api:
    build: 
      context: .
      dockerfile: search/Dockerfile
    volumes:
      - ./search:/usr/search
      - node_modules:/usr/search/node_modules
    tty: true
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ./geographic:/data
    command: osrm-routed --algorithm mld /data/japan-latest.osrm
  nominatim:
    image: mediagis/nominatim:4.2
    volumes:
      - ./geographic:/nominatim/data
      - ./nominatim-data:/var/lib/postgresql/14/main
    environment:
      - PBF_PATH=/nominatim/data/japan-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/asia/japan-updates/
    shm_size: 1gb
  optimization:
    build:
      context: .
      dockerfile: optimization/Dockerfile
    volumes:
      - ./optimization:/usr/optimization
    ports:
      - 8000:8000
    tty: true
    
volumes:
  node_modules:
